### ISSUE TITLE
[Guide] How to take screenshot evidence for issues

### ISSUE THREAD

**Issue by mrTheigen** [McFanta/Simple-Calculator#4]
<h3>1. Getting started</h3>
Hello there. Welcome to this guide of how to take screenshots on your computer for issues. Let's get started. In this guide I will show you two different ways of how to take screenshots on your computer.

<h3>The Default Screenshot Program</h3>

<h4>Finding the program</h4>
The default screenshot program which most windows computers have is called Snipping Tool. I am not actually sure if Mac has any standard snipping tool but it probably has but we will discuss that later. You can find the snipping tool by searching "Snipping Tool" or at least "snipping".

<h4>Using the snipping tool</h4>
To use the snipping tool just open the snipping tool program. Here is an example of how to take a screenshot with the snipping tool: 
![screenshot_374](https://cloud.githubusercontent.com/assets/17345169/14938149/28e441b8-0f1b-11e6-8c7c-d40581a2f203.png)

<h3>Lightshot</h3>

<h4>Downloading Lightshot</h4>
Lightshot is pretty much the same thing as the snipping tool but I prefer using lightshot instead of the snipping tool. Lightshot can be downloaded for Windows and Mac <a href="https://app.prntscr.com/en/index.html">here</a>. Here is some simple screenshots of how to install lightshot:
![screenshot_376](https://cloud.githubusercontent.com/assets/17345169/14938179/026d3bc4-0f1c-11e6-866c-0d740eac5b93.png)
![screenshot_377](https://cloud.githubusercontent.com/assets/17345169/14938181/08db5a04-0f1c-11e6-82f3-ff72b06c8dad.png)
![screenshot_378](https://cloud.githubusercontent.com/assets/17345169/14938184/0f97a604-0f1c-11e6-8d10-ad0f5f43c6a0.png)
![screenshot_379](https://cloud.githubusercontent.com/assets/17345169/14938185/15ad7262-0f1c-11e6-9c41-4b62c9049035.png)

<h4>Using Lightshot</h4>

Well lightshot works pretty much the same as the snipping tool but it's a lot easier to use in my opinion so you will probably understand it when you open the program. So that's that.

<h3>Thank you</h3>

I will be appreciated if this guide will be official and I will be really appreciated if you have checked out this guide and tried out the programs. If this guide gets added it will most likely be locked so I can't probably edit this guide so if that happens it's up to the collabrators and McFanta_ to update this guide. 

That's all for now.

Regards mrTheigen

**Comment by McFanta** [comment]
This guide looks great! Adding it now! :+1: 

I appreciate your help! :smile:

**Comment by mrTheigen** [comment]
You are welcome! :smile:

**Comment by McFanta** [comment]
Congratulations @mrTheigen! You have been selected as our first collabrator! Your task will be to deal with issues, pull requests, readme changes and guides. Please be careful before merging pull requests and changing files. I can always revert it but please be careful! Please don't comment on this issue though.

Have fun! :smile: 

Regards McFanta_!
